require_relative '../node_modules/react-native-macos/scripts/react_native_pods'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

abstract_target 'Shared' do
  target 'Reminders-macOS' do
    platform :macos, '12.0'

    config = use_native_modules!
    flags = get_default_flags()

    use_react_native!(
      :path => '../node_modules/react-native-macos',
      :hermes_enabled => false,
      :fabric_enabled => true,
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
  end
end
