require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

abstract_target 'Shared' do
  target 'Reminders-macOS' do
    platform :macos, '10.15'
    use_native_modules!
    use_react_native!(:path => '../node_modules/react-native-macos')
  end
end
